name: Build & Package WPEWebKit as .deb

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Package for ARM64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ninja-build cmake build-essential git fakeroot \
            g++-aarch64-linux-gnu gcc-aarch64-linux-gnu \
            qemu-user-static dpkg-dev dh-make devscripts \
            libglib2.0-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
            libjpeg-dev libpng-dev libharfbuzz-dev libwebp-dev \
            python3 python3-pip ruby unifdef

      - name: Clone WPEWebKit v2.48.4
        run: |
          git clone --branch wpewebkit-2.48.4 https://github.com/WebKit/WebKit.git
          cd WebKit
          mkdir build

      - name: Build WPEWebKit
        run: |
          cd WebKit/build
          cmake .. \
            -DPORT=WPE \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_INSTALL_PREFIX=/usr \
            -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
            -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
            -GNinja
          ninja
          DESTDIR=$GITHUB_WORKSPACE/deb-root ninja install

      - name: Create .deb package
        run: |
          mkdir -p deb-root/DEBIAN
          cat <<EOF > deb-root/DEBIAN/control
          Package: wpewebkit
          Version: 2.48.4
          Section: web
          Priority: optional
          Architecture: arm64
          Maintainer: Your Name <you@example.com>
          Description: WPE WebKit browser engine for embedded devices (Raspberry Pi 3B+)
          EOF

          fakeroot dpkg-deb --build deb-root wpewebkit-aarch64-rpi3b-v2.48.4.deb

      - name: Upload .deb to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v2.48.4
          name: WPEWebKit 2.48.4 for RPi3B+
          files: wpewebkit-aarch64-rpi3b-v2.48.4.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
