name: Build WPE WebKit from tarball

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build WPE WebKit 2.48.4 (arm64)

    steps:
      # ------------------------------------------------------------------
      # 1. Prepare the build machine
      # ------------------------------------------------------------------
      - name: Set up build environment
        run: |
          # Add arm64 architecture
          sudo dpkg --add-architecture arm64
          
          # Comprehensive cleanup of mirror configurations
          sudo rm -f /etc/apt/apt-mirrors.txt
          sudo rm -f /etc/apt/sources.list
          sudo rm -f /etc/apt/sources.list.d/*.list
          sudo rm -f /etc/apt/apt.conf.d/*mirror*
          sudo rm -f /etc/apt/apt.conf.d/*Mirror*
          
          # Temporarily disable mirrors to use direct sources
          echo 'Acquire::http::Pipeline-Depth "0";' | sudo tee /etc/apt/apt.conf.d/99-no-mirrors
          echo 'Acquire::http::No-Cache=True;' | sudo tee -a /etc/apt/apt.conf.d/99-no-mirrors
          
          # Clear apt cache to ensure clean state
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          
          # Create a single, architecture-scoped sources.list
          sudo tee /etc/apt/sources.list >/dev/null <<EOF
          # --- AMD64 ---
          deb [arch=amd64] http://azure.archive.ubuntu.com/ubuntu/ $(lsb_release -cs)          main restricted universe multiverse
          deb [arch=amd64] http://azure.archive.ubuntu.com/ubuntu/ $(lsb_release -cs)-updates  main restricted universe multiverse
          deb [arch=amd64] http://azure.archive.ubuntu.com/ubuntu/ $(lsb_release -cs)-backports main restricted universe multiverse
          deb [arch=amd64] http://azure.archive.ubuntu.com/ubuntu/ $(lsb_release -cs)-security main restricted universe multiverse

          # --- ARM64 (ports) ---
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ $(lsb_release -cs)          main restricted universe multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ $(lsb_release -cs)-updates  main restricted universe multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ $(lsb_release -cs)-backports main restricted universe multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ $(lsb_release -cs)-security main restricted universe multiverse
          EOF

          # Update package lists
          sudo apt-get update -qq

          # Fallback: If update fails, try with direct sources
          if [ $? -ne 0 ]; then
            echo "First apt update failed, trying fallback approach..."
            sudo rm -f /etc/apt/sources.list
            sudo rm -f /etc/apt/apt.conf.d/99-no-mirrors
            sudo tee /etc/apt/sources.list >/dev/null <<EOF
            deb http://archive.ubuntu.com/ubuntu/ $(lsb_release -cs) main restricted universe multiverse
            deb http://archive.ubuntu.com/ubuntu/ $(lsb_release -cs)-updates main restricted universe multiverse
            deb http://archive.ubuntu.com/ubuntu/ $(lsb_release -cs)-backports main restricted universe multiverse
            deb http://archive.ubuntu.com/ubuntu/ $(lsb_release -cs)-security main restricted universe multiverse
            deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ $(lsb_release -cs) main restricted universe multiverse
            deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ $(lsb_release -cs)-updates main restricted universe multiverse
            deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ $(lsb_release -cs)-backports main restricted universe multiverse
            deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ $(lsb_release -cs)-security main restricted universe multiverse
            EOF
            sudo apt-get clean
            sudo rm -rf /var/lib/apt/lists/*
            sudo apt-get update -qq
          fi

          # Install cross-compilation tool-chain + host tools
          sudo apt-get install -y \
            ninja-build cmake build-essential \
            g++-aarch64-linux-gnu gcc-aarch64-linux-gnu \
            qemu-user-static \
            python3 ruby unifdef fakeroot

          # Install ARM64 development libraries
          sudo apt-get install -y \
            libicu-dev:arm64 libharfbuzz-dev:arm64 \
            libglib2.0-dev:arm64 libgstreamer1.0-dev:arm64 \
            libgstreamer-plugins-base1.0-dev:arm64 \
            libjpeg-dev:arm64 libpng-dev:arm64 libwebp-dev:arm64 \
            libxml2-dev:arm64 libxslt1-dev:arm64 \
            libsqlite3-dev:arm64 libsoup2.4-dev:arm64

          # Clean up temporary apt configuration
          sudo rm -f /etc/apt/apt.conf.d/99-no-mirrors

      # ------------------------------------------------------------------
      # 2. Fetch WPE WebKit source
      # ------------------------------------------------------------------
      - name: Download WPE WebKit 2.48.4
        run: |
          wget -q https://wpewebkit.org/releases/wpewebkit-2.48.4.tar.xz
          tar -xf wpewebkit-2.48.4.tar.xz
          mv wpewebkit-2.48.4 wpewebkit

      # ------------------------------------------------------------------
      # 3. Configure & build
      # ------------------------------------------------------------------
      - name: Configure and build WPE WebKit
        run: |
          mkdir -p wpewebkit/build
          cd wpewebkit/build
          cmake .. \
            -DPORT=WPE \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_INSTALL_PREFIX=/usr \
            -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
            -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
            -GNinja
          ninja
          DESTDIR=$GITHUB_WORKSPACE/deb-root ninja install

      # ------------------------------------------------------------------
      # 4. Package
      # ------------------------------------------------------------------
      - name: Create .deb package
        run: |
          mkdir -p deb-root/DEBIAN
          cat <<EOF > deb-root/DEBIAN/control
          Package: wpewebkit
          Version: 2.48.4
          Section: web
          Priority: optional
          Architecture: arm64
          Maintainer: bhNibir <nibir@example.com>
          Description: WPE WebKit 2.48.4 built for Raspberry Pi 3B+
          EOF
          fakeroot dpkg-deb --build deb-root wpewebkit-aarch64-rpi3b-v2.48.4.deb

      # ------------------------------------------------------------------
      # 5. Release
      # ------------------------------------------------------------------
      - name: Upload release .deb package
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v2.48.4
          name: WPE WebKit 2.48.4 (Raspberry Pi 3B+)
          files: wpewebkit-aarch64-rpi3b-v2.48.4.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}